config/routes.rb
Rails.application.routes.draw do
  devise_scope :cashiers do
  end
  devise_for :cashiers
    get '/cashiers/sign_out' => 'devise/sessions#destroy'
  devise_for :admins do
    get '/admins/sign_out' => 'devise/sessions#destroy'
  end
  resources :cashiers
  resources :products do
    post 'change_status'
  end
  resources :orders
  resources :order_lines
  resources :homes
  root 'homes#index'
  get 'homes/index'
  get 'homes/show', as: :homes_show
  post '/orders/summary', to: 'orders#new', as: :order_summary #=> 'orders#create', as: :order_summary
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :models
  has_many :cashiers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
    #belongs_to :cashier
    attr_accessor :cashier_id, :total_price, :cash
    attr_writer :current_step
    has_many :order_lines#, :class_name => "OrderLine"
    accepts_nested_attributes_for :order_lines, 
                                allow_destroy: true,
                                :reject_if => :all_blank
  
    def current_step
        @current_step || steps.first
    end
    def steps
        %w[form summary]
    end
    def next_step
        self.current_step = steps[steps.index(current_step)+1]
    end
    def previous_step
        self.current_step = steps[steps.index(current_step)-1]
    end
    def last_step?
        current_step == steps.last
    end
    def first_step?
        current_step == steps.first
    end
    #def total_price
    #    self[:total_price]
    #end
    #def cash
    #    self[:cash]
    #end
    def cashier_id
        self[:cashier_id]
    end
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
    belongs_to :order
    has_many :products
    def price
        self[:price]
    end
    def quantity
        self[:quantity]
    end
end

app/models/product.rb
class Product < ApplicationRecord
    def name
        self[:name]
    end
    def price
        self[:price]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
  before_action :authenticate_admin!
  def new
      @cashier = Cashier.new
  end
  def create
    @cashier = Cashier.new(params[:cashier].permit(:email, :password, :password_confirmation))
    #@cashier.status = true
    #@cashier.errors.full_messages
    Cashier.create(email: @cashier.email, password: @cashier.password, password_confirmation: @cashier.password_confirmation)
    redirect_to @cashier
    #creating new cashier automatically logs in to the cashier
  end
  def sign_up
      @cashier = Cashier.new
  end
  def edit
    @cashier = Cashier.find(params[:id])
  end
  def update
    @cashier = Cashier.find(params[:id])
    if @cashier.update(cashier_params)
      redirect_to @cashier
    else
      render 'edit'
    end
  end
  def destroy
    @cashier = Cashier.find(params[:id])
    @cashier.destroy
    redirect_to cashiers_path
  end
  def show
    @cashier = Cashier.find(params[:id])
  end
  def index
    @cashiers = Cashier.all
  end
  private
    def cashier_params
        params.require(:cashier).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    before_action :authenticate_admin!, only: [:show]
    def index
    end
    def show
        @orders = Order.all
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_cashier!
    def new
        @order = Order.new
        @order.order_lines.build
        #@order.order_lines.each do |question|
        #    question.answers.build
        #end
    end
    def edit
    end
    def update
    end
    def create
        @order = Order.new(order_params)
        @cash = 0.0
        @order.order_lines.each do |n|
            n[:order_id] = @order.id
            @product = Product.find(n.product_id)
            n.price = @product[:price]
            @order[:total_price] ||= 0
            @order[:total_price] += (n.price * n.quantity)
        end
        @cash = @order[:cash]
        @order[:cash] = @order.cash
        @order[:cashier_id] = current_cashier.id
        @order[:date] = Date.today
        @order.save
        redirect_to @order
        #@order.save
        #redirect_to @order
    end
    def index
        @orders = Order.all
    end
    def destroy
        @order = Order.find(params[:id])
        @order.destroy
        redirect_to controller: 'orders'
    end
    def show
        @order = Order.find(params[:id])
    end
    def summary
        @order = Order.new(order_params)
        render '/orders/summary'
    end
    private
    def order_params
        params.require(:order).permit(:cash, :cashier_id, :total_price,  :order_lines_attributes => [ :product_id, :order_id, :quantity, :price ])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_admin!#, only: [:new, :edit, :update, :create, :destroy, :index, :show]
    #layout "application"
    def new
        @product = Product.new
    end
    def edit
        @product = Product.find(params[:id])
    end
    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to @product
        else
            render 'edit'
        end
    end
    def create
        @product = Product.new(params[:product].permit(:name, :price, :status))
        @product.status = true
        @product.save
        redirect_to @product
    end
    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to products_path
    end
    def show
        @product = Product.find(params[:id])
    end
    def index
        @products = Product.all
    end
    def change_status
        @product = Product.find(params[:id])
        if @product[:status] == true
            @product[:status] = false
        else
            @product[:status] = false
        end
    end
    private
        def product_params
            params.require(:product).permit(:name, :price, :status)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cashiers/edit.html.erb
<style>
    h1{
        font-size:50px;
        text-align:center;
    }
    #content{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:400px;
    }
    #content2{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:365px;
    }
    #content3{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:210px;
    }
    #content4{
        font-size:20px;
        text-align:center;
    }
</style>
<h1>Edit Cashier</h1>
<%= simple_form_for (@cashier) do |i| %>
<div id="content">
    <p>
        <%= i.input :email %>
    </p>
</div>

<div id="content2">
    <p>
        <%= i.input :password %>
    </p>
</div>

<div id="content3">
    <p>
        <%= i.input :password_confirmation %>
    </p>
</div>
<div id="content4">
    <p>
        <%= i.button :submit, class: 'btn btn-success' %>
    </p>
<% end %>
<%= link_to 'Back', cashiers_path, class: 'btn btn-primary btn-sm' %>
</div>
<!-- add password edit later -->

app/views/cashiers/index.html.erb
<style>
    h1{
        font-size:50px;
        text-align:center;
    }
    #content{
        font-size:50px;
        text-align:center;
    }
/*    #content2{
        font-family:Courier;
    }*/
</style>
<div id="content">
<h1>Cashiers</h1>
  <%= link_to 'New Cashier', new_cashier_path, class: 'btn btn-success' %>
</div>
<!--<div id="content2">-->
<table class="table table-striped">
  <tr>
    <th>Email</th>
    <!--<th>Availability</th>-->
    <th colspan="3"></th>
  </tr>
 
  <% @cashiers.each do |cashier| %>
    <tr>
      <td><%= cashier.email %></td>
      <td><%= link_to 'View', cashier_path(cashier), class: 'btn btn-primary' %></td>
      <td><%= link_to 'Edit', edit_cashier_path(cashier), class: 'btn btn-primary' %></td>
      <td><%= button_to 'Remove', cashier_path(cashier),
              method: :delete,
              class: 'btn btn-danger' %></td>
      <td colspan="2"></td>
    </tr>
  <% end %>
</table>
<!--</div>-->

app/views/cashiers/new.html.erb
<style>
    h1{
        font-size:50px;
        text-align:center;
    }
    #content{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:400px;
    }
    #content2{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:364px;
    }
    #content3{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:208px;
    }
    #content4{
        font-size:20px;
        text-align:center;
    }
</style>
<h1>Create a New Cashier!</h1>
<%= simple_form_for @cashier, url: cashiers_path do |i| %>
<div id="content">
    <p>
        <%= i.input :email %>
    </p>
</div>
<div id="content2">
    <p>
        <%= i.input :password %>
    </p>
</div>
<div id="content3">
    <p>
        <%= i.input :password_confirmation %>
    </p>
</div>
<div id="content4">
    <p>
        <%= i.button :submit, class: 'btn btn-success' %>
    </p>
<% end %>
<%= link_to 'Back', cashiers_path, class: 'btn btn-primary btn-sm' %>
</div>

app/views/cashiers/show.html.erb
<style>
    h1{
        font-size:50px;
        text-align:center;
    }
    #content{
        font-size:20px;
        font-family:Courier;
        text-align:center;
    }
    #content2{
        font-size:20px;
        text-align:center;
    }
</style>
<h1>Cashier Information</h1>
<div id="content">
<p>
    <strong>Cashier Email: </strong><%= @cashier.email %>
</p>
</div>
<% @orders = Order.all %>
<h2>Orders Made</h2>
<table class="table table-striped">
    <tr>
        <th>Total Price</th>
        <th>Cash</th>
        <th colspan="4"></th>
    </tr>
    <% @orders.each do |order| %>
        <% if order[:cashier_id] == @cashier[:id] %>
        <tr>
          <td><%= order[:total_price] %></td>
          <td><%= order[:cash] %></td>
        </tr>
        <% end %>
    <% end %>
</table>

<div id="content2">
<%= link_to 'Edit', edit_cashier_path(@cashier), class: 'btn btn-success btn-sm' %>
<%= link_to 'Back', cashiers_path, class: 'btn btn-primary btn-sm' %>
</div>

app/views/homes/index.html.erb
<style>
    h1{
        font-size:70px;
        font-family:Times;
        text-align:center;
    }
    #content{
        font-size:20px;
        font-family:Courier;
        text-align:center;
    }
    #content2{
        font-size:20px;
        font-family:Courier;
        text-align:center;
    }
</style>
<h1>Welcome to the POS System</h1>
<% if cashier_signed_in? %>
<div id="content">
    <p>
        Click "Order List" on the top bar to start creating orders.
    </p>
</div>
<% elsif admin_signed_in? %>
<div id="content2">
    <p>
        As an admin, you can create products, cashiers and look at the daily report. 
    </p>
</div>
<% else %>
    <h2>Sign in as Admin</h2>
    <%= simple_form_for :admin, url: admin_session_path do |f| %>
      <%= f.input :email %> <br>
      <%= f.input :password %> <br>
      <%= f.button :submit, "Sign in", class: "btn btn-primary" %> <br>
    <% end %>
    <h2>Sign in as Cashier</h2>
    <%= simple_form_for :cashier, url: cashier_session_path do |f| %>
      <%= f.input :email %> <br>
      <%= f.input :password %> <br>
      <%= f.button :submit, "Sign in", class: "btn btn-primary" %> <br>
    <% end %>
<% end %>

app/views/homes/show.html.erb
<style>
    h2{
        font-size:50px;
        font-family:Courier;
        text-align:center;
    }
/*    #content{
        font-family:Courier;
    }*/
</style>
<h2>Daily Report</h2>
<!--<div id="content">-->
<table class="table table-striped">
    <tr>
        <th>Order ID</th>
        <th>Cashier</th>
        <th>Orders</th>
        <th>Total Price</th>
        <th>Cash</th>
        <th>Change</th>
        <th colspan="4"></th>
    </tr>
<% @orders.each do |n| %>
    <tr>
    <% if n[:date] = Date.today %>
        <% @cashier = Cashier.find(n[:cashier_id]) %>
        <th><%= n[:id] %></th>
        <th><%= @cashier[:email] %></th>
        <th>
              <% n.order_lines.each do |order| %>
              <% @product = Product.find(order.product_id) %>
              <p>
                  <%= @product[:name] %> - <%= order[:quantity] %>
              </p>
              <% end %>
        </th>
        <th><%= n[:total_price] %></th>
        <th><%= n[:cash] %></th>
        <th><%= n[:cash] - n[:total_price] %></th>
    <% end %>
    </tr>
<% end %>
</table>
<!--</div>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>POS System MIS21</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">POS System</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <% if admin_signed_in? %>
                  <li>
                    <%= link_to "Products", products_path %>
                  </li>
                  <li>
                    <%= link_to "Cashiers", cashiers_path %>
                  </li>
                  <li>
                    <%= link_to "Daily Report", homes_show_path %>
                  </li>
                <% elsif cashier_signed_in? %>
                  <li>
                    <%= link_to 'Order List', controller: 'orders' %>
                  </li>
                <% end %>
              </ul>
          
              <p class="navbar-text pull-right">
                <% if admin_signed_in? %>
                  Logged in as <strong><%= current_admin.email %></strong>.
                  <%# link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> 
                  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
                <% elsif cashier_signed_in? %>
                  Logged in as <strong><%= current_cashier.email %></strong>.
                  <%= link_to 'Log Out', destroy_cashier_session_path, method: :delete, :class => 'navbar-link' %>
                <% end %>
              </p>
            </div>
          </div>
        </nav>

    <div class="container">

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/layouts/backupapplication.html.1.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
  <h3>Orders</h3>
  <div id='tasks'>
    <%= f.simple_fields_for :order_lines do |ol| %>
      <%= render 'order_line_fields', f: ol %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'Add Product', f, :order_lines, class: 'btn btn-primary'%>
    </div>
    <%= f.input :cash, required: true %>
  </div>

app/views/orders/_order_line_fields.html.erb
    <div class="nested-fields">
        <%= f.collection_select :product_id, Product.where(status: true), :id, :name %>
        <%= f.input :quantity, label: false, required: true %>
    </div>

app/views/orders/_summary.html.erb
<h3>Confirm Order</h3>
<%= debug @order %>
<%= debug @order.order_lines %>
<% @order.order_lines.each do |n| %>
    <% @product = Product.find(n.product_id) %>
    <p>
    <%= h @product.name %>
    </p>
    <p>
    <%= h n.price %>
    </p>
    <p>
    <%= h n.quantity %>
    </p>
<% end %>
<p>
  <%= h @order.total_price %>
</p>
  <%= f.hidden_field :total_price, value: @order.total_price %>
  <%= f.input :cash %>

app/views/orders/backup_summary.html.1.erb
<h3>Confirm Order</h3>
  <%= @order.order_lines.each do |n| %>
      <% @product = Product.find(n.product_id) %>
      <p>
          <%= @product.name %>
      </p>
      <p>
          <%= n.price %>
      </p>
      <p>
          <%= n.quantity %>
      </p>
  <% end %>
  <%= f.input :cash %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>

app/views/orders/index.html.erb
<style>
    h1{
        font-size:50px;
        font-family:Courier;
        text-align:center;
    }
    #link{
       /* font-family:Courier;*/
        text-align:center;
    }
/*    #content{
        font-family:Courier;
    }*/
</style>
<h1>Orders</h1>
<div id="link">
<%= link_to 'New Order', new_order_path, class: 'btn btn-success' %>
</div>
<!--<div id="content">-->
<table class="table table-striped">
    <tr>
        <th>Cashier</th>
        <th>Total Price</th>
        <th>Cash</th>
        <th>Orders</th>
        <th colspan="4"></th>
    </tr>
    <% @orders.each do |order| %>
    <% @cashier = Cashier.find(order[:cashier_id]) %>
        <tr>
          <td><%= @cashier[:email] %></td>
          <td><%= order[:total_price] %></td>
          <td><%= order[:cash] %></td>
          <td>
              <% order.order_lines.each do |n| %>
              <% @product = Product.find(n.product_id) %>
              <p>
                  <%= @product[:name] %> - <%= n[:quantity] %>
              </p>
              <% end %>
          </td>
          <td><%= link_to 'View', order_path(order), class: 'btn btn-primary' %></td>
        </tr>
    <% end %>
</table>
<!--</div>-->

app/views/orders/new.html.erb
<h1>New Order</h1>
<%= simple_form_for @order do |f| %>
    <%= f.error_notification %>
    <%= render 'form', :f => f %>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

<%= link_to "Back to List", orders_path, class: "btn btn-primary btn-sm" %>

app/views/orders/show.html.erb
<style>
    h1{
        font-size:50px;
        font-family:Courier;
        text-align:center;
    }
    #content{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:400px;
    }
    #content2{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:400px;
    }
    #content3{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:400px;
    }
    #content4{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:400px;
    }
    #content5{
        font-size:20px;
        text-align:center;
    }
</style>
<h1>Order Information</h1>

<div id="content">
<p>
    <strong>Order No. : </strong><%= @order[:id] %>
</p>
</div>

<div id="content2">
<p>
    <strong>Order Total Price: </strong><%= @order[:total_price] %>
</p>
</div>

<div id="content3">
<p>
    <strong>Order Cash: </strong><%= @order[:cash] %>
</p>
</div>

<div id="content4">
<p>
    <strong>Date of Purchase: </strong><%= @order[:date] %>
</p>
</div>

<div id="content5">
<%= link_to 'Back', orders_path, class: 'btn btn-primary btn-sm' %>
</div>

app/views/products/edit.html.erb
<style>
    h1{
        font-size:50px;
        text-align:center;
    }
    #content{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:400px;
    }
     #content2{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:388px;
    }
    #content3{
        font-size:20px;
        text-align:center;
    }
</style>
<h1>Edit Product</h1>
<%= simple_form_for (@product) do |i| %>
<div id="content">
    <p>
        <%= i.input :name %>
    </p>
</div>
<div id="content2">
    <p>
        <%= i.input :price %>
    </p>
</div>
<div id="content3">
    <p>
        <%= i.button :submit, class: 'btn btn-success' %>
    </p>
<% end %>
<%= link_to 'Back', products_path, class: 'btn btn-primary btn-sm' %>
</div>

app/views/products/index.html.erb
<style>
    h1{
        font-size:50px;
        font-family:Courier;
        text-align:center;
    }
/*    #content{
        font-family:Courier;
    }*/
    #links{
        font-size:50px;
        text-align:center;
        margin-left:0px;
    }
</style>

<h1>Product List</h1>

<div id = "links">
<%= link_to 'New Product', new_product_path, class: 'btn btn-success' %>
</div>

<!--<div id='content'>-->
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <!--<th>Availability</th>-->
    <th colspan="3"></th>
  </tr>
 
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <% ztatuz = '' %>
      <% change = false %>
      <% if product.status==true %>
        <% ztatuz = 'Deactivate' %>
        <% change = false %>
      <% else %>
        <% ztatuz = 'Activate' %>
        <% change = true %>
      <%end%></td>
      <% @product = product %>
      <td><%= link_to 'View', product_path(product), class: 'btn btn-primary' %></td>
      <td><%= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary' %></td>
      <td><%= link_to ztatuz, product_path(@product, :product => {:status => change}), method: :put, class: 'btn btn-danger' %></td>
      <td colspan="2"></td>
    </tr>
  <% end %>
</table>
<!--</div>-->

app/views/products/new.html.erb
<style>
    h1{
        font-size:50px;
        text-align:center;
    }
    #content{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:400px;
    }
    #content2{
        font-size:20px;
        font-family:Courier;
        text-align:left;
        margin-left:388px;
    }
    #content3{
        font-size:30px;
        text-align:center;
    }
</style>
<h1>Create a New Product!</h1>


<%= simple_form_for @product do |i| %>
<div id="content">
    <p>
        <%= i.input :name %>
    </p>
</div>
<div id="content2">
    <p>
        <%= i.input :price %>
    </p>
</div>
<div id="content3">
    <p>
        <%= i.button :submit, class: 'btn btn-success' %>
    </p>
<% end %>
    <p>
        <%= link_to 'Back', products_path, class: 'btn btn-primary btn-sm' %>
    </p>
</div>

app/views/products/show.html.erb
<style>
    h1{
        font-size:50px;
        text-align:center;
    } 
    #content
    {
        font-size:20px;
        font-family: Courier;
        text-align: left;
        margin-left:380px;
    }
    
    #content2{
        font-size:20px;
        text-align:center;
    }
</style>
<h1>Product Information</h1>
<div id = "content">
<p>
    <strong>Product Name: </strong><%= @product.name %>
</p>
<p>
    <strong>Product Price: </strong><%= @product.price %>
</p>
<p>
    <strong>Product Availability: </strong><!--<%= @product.status %>-->
    <% if @product.status==true %>
        <%= 'Available' %>
    <% else %>
        <%= 'Unavailable' %>
    <%end%>
</p>
</div>

<div id = "content2">
<%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-success btn-sm' %>
<%= link_to 'Back', products_path, class: 'btn btn-primary btn-sm' %>
</div>